name: Java CI with Maven - Dev branch
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
          chmod +x ./InstallChrome.sh
                      ./InstallChrome.sh
      - name: Build
        run: mvn -B clean package -DskipTests
      - name: Run tests
        run: mvn -B clean verify -Pheadless-mode
